sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
before_install:
  - rm -rf node_modules
  - npm install -g ganache-cli
install:
  - npm install
before_script:
  - npm run rpc
  - sleep 5