sudo: required
dist: trusty
language: node_js
node_js:
  - '8'
before_install:
  - rm -rf node_modules
install:
  - npm install
script:
  - npm run solium && npm run lint && npm test
before_script:
  - npm run rpc > /dev/null &
  - sleep 5